### ISSUE TITLE
Create a tslint.json/.eslintrc for these rules?

### ISSUE THREAD

**Issue by bcherny** [vhf/v8-bailout-reasons#6]
May be out of scope for this repo.

**Comment by vhf** [comment]
Thanks for the suggestion @bcherny !

By `tslint.json`/`.eslintrc`, do you mean creating linting rules for ts and eslint to warn people about these optimization issues?

If yes, I also think it's probably out of scope. I wouldn't have time to maintain them. This would require a great amount of work because these bailouts are fast moving targets.

I think it would be great to have some tests though. I'm not sure how much work it would require, but I'd love to have all these examples run on various node versions through travis.

**Comment by bcherny** [comment]
> By tslint.json/.eslintrc, do you mean creating linting rules for ts and eslint to warn people about these optimization issues?

That's right! If the target is fast moving, I wonder if it would be possible to generate linter rules from some other source of truth, similar to caniuse. Judging from how complex the grammar for eslint rules is, the answer is probably not.

I also wonder if there are some core bailout reasons that aren't going to change anytime soon (eg. try/catch), and if it's possible to write rules for them. Will track this idea somewhere else.

**Comment by vhf** [comment]
> I also wonder if there are some core bailout reasons that aren't going to change anytime soon (eg. try/catch), and if it's possible to write rules for them. Will track this idea somewhere else.

try/catch seems to be a safe bet, I could think of a few others as well. It's also kinda easy to stay one step ahead because these bailout reasons are kept in V8 repo and they disappear from the master there days/weeks before any Chrom(e|ium) release. TurboFan is bound to replace Crankshaft, and as soon as Crankshaft is completely disabled many things will change.

If you track this somewhere else, could you please ping me from there? I'd love to follow the effort and maybe contribute!
